### ISSUE TITLE
Question about CLAP score evaluation

### ISSUE THREAD

**Issue by IFICL** [happylittlecat2333/Auffusion#11]
Hi,

In your repo, you mentioned that you use https://huggingface.co/laion/clap-htsat-unfused to compute the CLAP score and I am trying to reproduce the same evaluation. However, I noticed that the weights of CLAP are trained with a sampling rate of 48K but your model only produces the audio with a sampling rate of 16K.

I wonder how you perform the evaluation. Did you upsampling the audio by the off-shelf models?

**Comment by happylittlecat2333** [comment]
Actually, all open-sourced CLAP are trained on 48K sample rate audio. We follow [huggingface CLAP scripts](https://huggingface.co/docs/transformers/model_doc/clap#transformers.ClapModel) to get the text_embeds and audio_embeds, and follow the [original LAION-AI CLAP scripts](https://github.com/LAION-AI/CLAP) to use librosa to upsample the audio. Therefore the code can be:

```python
model = ClapModel.from_pretrained("laion/clap-htsat-unfused").to(device)
processor = AutoProcessor.from_pretrained("laion/clap-htsat-unfused")

audio_sample, sampling_rate = librosa.load(audio_path, sr=48000)
audio_sample = librosa.util.normalize(audio_sample)

inputs = processor(text=text, audios=audio_sample, sampling_rate=sampling_rate, return_tensors="pt", padding=True).to(device)

outputs = model(**inputs)

text_embeds = outputs.text_embeds
audio_embeds = outputs.audio_embeds
```

**Comment by IFICL** [comment]
Thanks for the answer and code.
