### ISSUE TITLE
About pad_spec

### ISSUE THREAD

**Issue by Vincent2311** [happylittlecat2333/Auffusion#12]
I'm using notebooks/inpainting.ipynb and I want to custome the input audio length. According to my understanding, I need to change `1024` in `pad_spec` to `int(duration * 1024 / 10)` right? However, I notice that in `pad_spec`, there's one assert line saying `assert spec_length % 8 == 0, "spec_length must be divisible by 8"`. Is there any specific reason to constrain the spec_length be divisible by 8?

**Comment by happylittlecat2333** [comment]
Apologies for the late reply. Since the VAE of Auffusion is based on StableDiffusion and has a compression rate of 8, the spec_length must be a multiple of 8.
