### ISSUE TITLE
the code for the  audio-to-audio generation

### ISSUE THREAD

**Issue by hello-xiaow** [happylittlecat2333/Auffusion#5]
This is a very exciting job！！
I see the  audio-to-audio generation part has been completed in the todo list, but I couldn't find it
can you tell me where is the inference code for the  audio-to-audio generation？

**Comment by happylittlecat2333** [comment]
You can find the code in [notebooks](https://github.com/happylittlecat2333/Auffusion/blob/main/notebooks/README.md) where `Text-guided style transfer` refers to audio-to-audio generation.

**Comment by hello-xiaow** [comment]
a prompt must be provided to achieve Text-guided style transfer. 
Is there a code that does not require a prompt，only audio-to-audio generation？

**Comment by happylittlecat2333** [comment]
I have not try this scenario yet, but maybe you can just let `prompt=""` to disable prompt, just audio-audio generation only control by strength.

**Comment by hello-xiaow** [comment]
get it, Thank you vrey much for your answer
